timezones = [
    ('Alaska', -9.0),
    ('Pacific Time (US & Canada)', -8.0),
    ('Arizona', -7.0),
    ('Mountain Time (US & Canada)', -7.0),
    ('Central Time (US & Canada)', -6.0),
    ('Eastern Time (US & Canada)', -5.0),
    ('Indiana (East)', -5.0),
    ('International Date Line West', -11.0),
    ('Midway Island', -11.0),
    ('Samoa', -11.0),
    ('Tijuana', -8.0),
    ('Chihuahua', -7.0),
    ('Mazatlan', -7.0),
    ('Central America', -6.0),
    ('Guadalajara', -6.0),
    ('Mexico City', -6.0),
    ('Monterrey', -6.0),
    ('Saskatchewan', -6.0),
    ('Bogota', -5.0),
    ('Lima', -5.0),
    ('Quito', -5.0),
    ('Atlantic Time (Canada)', -4.0),
    ('Caracas', -4.0),
    ('La Paz', -4.0),
    ('Santiago', -4.0),
    ('Newfoundland', -3.5),
    ('Brasilia', -3.0),
    ('Buenos Aires', -3.0),
    ('Georgetown', -3.0),
    ('Greenland', -3.0),
    ('Mid-Atlantic', -2.0),
    ('Azores', -1.0),
    ('Cape Verde Is.', -1.0),
    ('Casablanca', 0.0),
    ('Dublin', 0.0),
    ('Edinburgh', 0.0),
    ('Lisbon', 0.0),
    ('London', 0.0),
    ('Monrovia', 0.0),
    ('Amsterdam', 1.0),
    ('Belgrade', 1.0),
    ('Berlin', 1.0),
    ('Bern', 1.0),
    ('Bratislava', 1.0),
    ('Brussels', 1.0),
    ('Budapest', 1.0),
    ('Copenhagen', 1.0),
    ('Ljubljana', 1.0),
    ('Madrid', 1.0),
    ('Paris', 1.0),
    ('Prague', 1.0),
    ('Rome', 1.0),
    ('Sarajevo', 1.0),
    ('Skopje', 1.0),
    ('Stockholm', 1.0),
    ('Vienna', 1.0),
    ('Warsaw', 1.0),
    ('West Central Africa', 1.0),
    ('Zagreb', 1.0),
    ('Athens', 2.0),
    ('Bucharest', 2.0),
    ('Cairo', 2.0),
    ('Harare', 2.0),
    ('Helsinki', 2.0),
    ('Istanbul', 2.0),
    ('Jerusalem', 2.0),
    ('Kyev', 2.0),
    ('Minsk', 2.0),
    ('Pretoria', 2.0),
    ('Riga', 2.0),
    ('Sofia', 2.0),
    ('Tallinn', 2.0),
    ('Vilnius', 2.0),
    ('Baghdad', 3.0),
    ('Kuwait', 3.0),
    ('Moscow', 3.0),
    ('Nairobi', 3.0),
    ('Riyadh', 3.0),
    ('St. Petersburg', 3.0),
    ('Volgograd', 3.0),
    ('Tehran', 3.5),
    ('Abu Dhabi', 4.0),
    ('Baku', 4.0),
    ('Muscat', 4.0),
    ('Tbilisi', 4.0),
    ('Yerevan', 4.0),
    ('Kabul', 4.5),
    ('Ekaterinburg', 5.0),
    ('Islamabad', 5.0),
    ('Karachi', 5.0),
    ('Tashkent', 5.0),
    ('Chennai', 5.5),
    ('Kolkata', 5.5),
    ('Mumbai', 5.5),
    ('New Delhi', 5.5),
    ('Kathmandu', 5.75),
    ('Almaty', 6.0),
    ('Astana', 6.0),
    ('Dhaka', 6.0),
    ('Novosibirsk', 6.0),
    ('Sri Jayawardenepura', 6.0),
    ('Rangoon', 6.5),
    ('Bangkok', 7.0),
    ('Hanoi', 7.0),
    ('Jakarta', 7.0),
    ('Krasnoyarsk', 7.0),
    ('Beijing', 8.0),
    ('Chongqing', 8.0),
    ('Hong Kong', 8.0),
    ('Irkutsk', 8.0),
    ('Kuala Lumpur', 8.0),
    ('Perth', 8.0),
    ('Singapore', 8.0),
    ('Taipei', 8.0),
    ('Ulaan Bataar', 8.0),
    ('Urumqi', 8.0),
    ('Osaka', 9.0),
    ('Sapporo', 9.0),
    ('Seoul', 9.0),
    ('Tokyo', 9.0),
    ('Yakutsk', 9.0),
    ('Adelaide', 9.5),
    ('Darwin', 9.5),
    ('Brisbane', 10.0),
    ('Canberra', 10.0),
    ('Guam', 10.0),
    ('Hobart', 10.0),
    ('Melbourne', 10.0),
    ('Port Moresby', 10.0),
    ('Sydney', 10.0),
    ('Vladivostok', 10.0),
    ('Magadan', 11.0),
    ('New Caledonia', 11.0),
    ('Solomon Is.', 11.0),
    ('Auckland', 12.0),
    ('Fiji', 12.0),
    ('Kamchatka', 12.0),
    ('Marshall Is.', 12.0),
    ('Wellington', 12.0),
    ("Nuku'alofa", 13.0)
]